:title: Building the Docs Site with an SSG
:relativeLocation:
:ancestorPath: .

// ifndef::env-gitlab[]
// include::{ancestorPath}/includes/adoc-header.adoc[]
// endif::[]

:imagesDir: ./images
:includcesDir: ./includes
:program: my-program
:scmHostname: github.com
:scmToplevel: DryHumorInDC
:scmUriPrefix: https://{scmHostname}/{scmToplevel}
:scmUriPrefixDocs: {scmUriPrefix}/{scmToplevelDocs}/relativeLocation}
:toc:
:toclevels: 4
:sectnums:
:toc-placement: left
:setanchors:
:setlinks:
:xrefstyle: short
:sectanchors:
:webfonts!:
:icons: font
:iconfont-remote!:
:iconfont-name: fontawesome-min-4.6.1
:stylesdir: {ancestorPath}/css
//- :bl: pass:[ +]
//- = {title}

//- toc::[]

ifeval::["{filetype}" == "html"]
pass:[<link rel="stylesheet" href="]{ancestorPath}/pass:[css/asciinema-player.css" />]
pass:[<script scr="]{ancestorPath}/pass:[javascript/asciinema-player.js"></script>]
endif::[]

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::env-gitlab[]
:outfilesuffix: .adoc
endif::[]

ifndef::env-gitlab[]
ifeval::["{docname}" != "toplevel-thing"]
ifeval::["filetype}" != "pdf"]
link:{ancestorPath/toplevel-thing{outfilesuffix}[Return to Top-Level Docs]
endif::[]
endif::[]
endif::[]

ifdef::env-gitlab[]
''''
:docname: Readme
:outfilesuffix: .adoc
== *IMPORTANT*: I see...
''''
endif::[]

=== Options Considered
The following toolchains have been considered:

[cols="1,1,1,1", frame="none", grid="none"]
|===
a|* ADOC/Antora
a|* ADOC/docToolchain
a|* MD/Hugo
a|* MD/mkdocs

a|* MDX/Gatsby.sh
a|* MDX/Docusaurus
a|* RST/mkdocs
a|* RST/Sphinx
|===

Ultimately, a docker image will be created for running the SSG.  In the meantime, the manual steps are listed below.  Once we have a suitable docker image, the Dockerfile will suffice as the setup procedcure for getting the SSG to run.  Those steps are defined in the following subsections.

==== Markup

===== Asciidoc

===== GFM (Github-Flavored Markdown)

===== MDX (Markdown with JSX)

===== RST (ReStructured Text)

==== SSG

===== Antora
This option deserves a lot of investigation.  I'm very intrigued by this, given that Dan Allen (createor of asciidoctor) is leading this new project.  They address many shortcomings of existing SSGs.  Now that _Awestruct_ (above) is no longer the SSG used to publish https://docs.asciidoctor.org, we can safely conclude that Antora is being dogfooded by Dan Allen.  This gives a lot of confidence in using it.  It also appears that the search index is fully implemented (lunr).

===== docToolchain

===== Docusaurus

===== Gatsby.js
Javascript framework that expects Markdown as input.  It does mention _extended_ markdown, but that may not be necessary; would have to experiment.  On the surface, Gatsby looks like it has a pretty rich ecosystem fof plugins, and it is nice that it serves up ReactJS webpage, given how cool that is!  People would be interested in getting good with that since it is not a wasted skill to learn ReactJS.

===== Hugo

===== MkDocs
This is fairly well proven in many enterprises and foss initiatives.  The disadvantage of using MkDocs is the same central argument against Markdown in general -- it is only useful when you extend it in a non-standard way.  For example, the expressiveness in MkDocs comes from using _Python-MarkDown_, not the basic markdown syntax.  Again -- there is only one specification for feature-complete documentation formats such as ReST (ReStructured Text) and asciidoc.

=== Real World Examples
WARNING: This section is biased; it is based on Matt's personal assessment.

<<table-static-sites-we-like>> lists a handful of statically generated sites that we like the look of.  There are some with each type of markup syntax, and it should be noted that each SSG tends to have a preferred markup.

[[table-static-sites-we-like]]
.Statically generated sites we like
[cols="6*",uframe="none", grid="none", options="header"]
|===
|Docs Site
|URL
|Markup Syntax
|SSG
|Notes
|SSG Trend ^*(1)*^

|Ansible +
Django +
Python +
cmake +
kernel.org +
offline help docs in Gnome
|https://docs.ansible.com/ansible/latest/index.html +
https://docs.djangoproject.com +
https://pythondotorg.readthedocs.io +
https://docs.python.org/3/ +
https://kernel.org +
https://cmake.org +
file:///usr/share/doc/terminator/html/index.html
|RST
|Sphinx
|
|Hot

|ReactJS Docs +
OpenFDA +
Algolia
|https://reactjs.org/docs/getting-started.html +
https://docsearch.algolia.com/docs/what-is-docsearch +
https://open.fda.gov
|MDX
|Gatsby.js
|
|Hot

|Docusaurus +
ReactNative
|https://jestjs.io/docs/getting-started +
https://reactnative.dev/docs/getting-started
|MDX
|Docusaurus (Facebook)
|*(7)*
|Hot

|docToolchain +
Arc42 +
htmlSanityCheck
|https://doctoolchain.org/docToolchain/v2.0.x/index.html +
https://arc42.org/documentation/ +
https://aim42.github.io/htmlSanityCheck
|Asciidoc
|docToolchain
|
|Active

|Hugo Docs +
Kubernetes +
Helm +
etcd +
Docker
|https://gohugo.io/documentation +
https://kubernetes.io/docs/home +
https://helm.sh/docs +
https://etcd.io/docs/latest +
https://docs.docker.com (used to be Jekyll)
|Markdown preferred, asciidoc allowed
|Hugo
|
|Hot

|Gradle
|https://docs.gradle.org
|Asciidoc
|Custom
|
|Cold (Used one place)

|Microsoft
|https://docs.microsoft.com
|CommonMark-flavored Markdown & Custom Markdown extensions
|OpenPublishing, Microsoft Proprietary?
|*(2)*
|Dormant

|Spring
|https://docs.spring.io
|asciidoc
|Middleman
|
|Dormant

|Ping Identity
|https://docs.pingidentity.com
|DITA
|DITA Open Toolkit
|*(5)*
|Dormant

|Groovy Docs & Jenkins Docs
|https://groovy-lang.org/install.html +
https://www.jenkins.io/doc/book/installing/
|asciidoc
|Awestruct
|
|Dormant

|Antora Docs +
Asciidoctor Docs +
CentOS Docs +
Solr Docs +
Eclipse Che
|https://docs.antora.org +
https://docs.asciidoctor.org +
https://docs.centos.org +
https://solr.apache.org/guide +
https://eclipse.dev/che/docs
|asciidoc
|Antora
|
|Active

|Elastic
|https://elastic.co/guide
|asciidoc
|Custom Perl script & Jekyll
| *(3)*
|Active

|Prometheus & Github
|https://prometheus.io/docs/introduction/overview +
https://docs.github.com +
https://nanoc.app/about
|Markdown (asciidoc supported)
|Nanoc
|*(5)*
|Dormant

|AWS
|https://docs.aws.amazon.com/
|Github-Flavored Markdown & RST
|Sphinx & custom python script.
|
|Hot

|ReadTheDocs
|https://docs.readthedocs.io
|RST
|mkdocs
|*(4)*
|Hot

|Openshift
|https://docs.openshift.com
|asciidoc
|AsciiBinder
|
|Dormant
|===

NOTE: *(1)* We used the number of Git stargazers and Twitter followers to determine the (albeit somewhat subjectively) if the SSG is _HJot_, _Active_, or _Dormant_.  If there are active commits and issue activity, it is at the very least: _Active_.  If it's the top-25 in link:https://staticgen.com[] -- and >= 0.3% growth in git(hub/lab) stars in the past week -- then it's _Hot_.  Anything else would be considreed dormant.

TIP: *(2)* Excellent techdoc writer's style guide: https://docs.microsoft.com/en-us/style-guide

NOTE: *(3)* This site seems to be the easiest transition for us.  Asciidoc is a 1st class citizen.  In fact, it is used to host the Antora docs, a beautiful, indexed site, written in asciidoc.  The fact that the _asciidoctor_ author uses it to publish said docs using htis SSG is a good fit for us.  It has a local index, albeit built with an indexing service.  I'm sure we can get this to work with a local index (e.g. Lunr).

WARNING: *(4)* readthedocs.io warns against using Markdown syntax in favor of RST.  Great article here: https://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs

NOTE: *(5)* This may be the most impressive set of docs I've seen, from the perspective of single-source component reuse.  That said, I think this would be more suitable for a fortune-500 company that is willing to support a tech writing department hat can commit to writing in an obscure source format.  DITA is an XML format, and for the pleasant writing experience, this requires  COTS XML editors like OxygenXML, or something like Adobe Framemaker.  The experience is superior to other approaches in how it allows an author to control perspective and scope of documentation, while maintaing creative control of layout, but again -- overkill for what we are trying to do at the project level.  CommonMark can be used as the source, but it requires constant transforming to DITA to stay useful.

NOTE: *(6)* Nanoc should get an honorable mention here, despite it being labeled as _dormant_.  Rationale: It is used by some heavy hitters, namely: GitLab and Prometheus.

NOTE: *(7)* Facebook is not completely dogfooding _Docusaurus_.  It appears they are using a combindation of _Docusaurus_ and _Gadsby.js_.




