---

- hosts: localhost

  tasks:

  - debug:
      var: ansible_distribution

  - name: Install Homebrew
    include_role:
      name: ansible-homebrew
    when: ansible_distribution == "MacOSX"

  - name: Install Misc Tooling
    include_role:
      name: ansible-misc-tools

  - name: Install Chrome
    include_role:
      name: ansible-chrome
      apply:
        ignore_errors: yes

  - name: Configure nodejs
    include_role:
      name: ansible-nodejs
      apply:
        ignore_errors: yes

  - name: Install and configure visual studio code
    include_role:
      name: ansible-vscode

  - name: Install AWS Tooling
    include_role:
      name: ansible-aws


